### ISSUE TITLE
null safety

### ISSUE THREAD

**Issue by barbalex** [tlserver/flutter_map_location_marker#3]
flutter_map is being upgraded: https://github.com/fleaflet/flutter_map/pull/870.

Dependencies need to be upgraded: 
- geolocator and flutter_compass already have null safe versions
- use latlong2 instead of latlong, like flutter_map does (https://github.com/fleaflet/flutter_map/blob/master/pubspec.yaml#L14)

The code needs to be migrated: https://dart.dev/null-safety/migration-guide#step2-migrate.

I tried to fork and do it but got stuck.

**Comment by danielocampo2** [comment]
@barbalex I was coming here to report the same thing, but I see something strange regarding this plugin's versions. Master's latest version is 0.0.5 and it's been updated Nov 2021, while in pub.dev latest version is from April (0.0.8):
https://pub.dev/packages/flutter_map_location_marker/versions

**Comment by tlserver** [comment]
Yes, I also receive a PR for this 8 hours ago. Also, I found around 3 forks already migrated to null-safety.

**Comment by tlserver** [comment]
Null-safety version is ready on github now.

Null-safety flutter_map is currently available on github only and pub.dev do not accept git source dependency, so I am not able to publish to pub.dev now. Please use git source in your project for current state if needed.

In pubspec.yaml:
```
dependencies:
  flutter_map_location_marker:
    git:
      url: https://github.com/tlserver/flutter_map_location_marker
      ref: null-safety
```
