### ISSUE TITLE
FMLM does not support Flutter Map 4.

### ISSUE THREAD

**Issue by elliottetzkorn** [tlserver/flutter_map_location_marker#62]
When using the dev branch, flutter_map: ^4.0.0-dev.1, which Flutter Map is officially suggesting users begin migrating to, this location marker package breaks and prevents the upgrade.

**Comment by tlserver** [comment]
Nothing break with FMLM v5.3.0 and FM v4 0.0-dev.1 when I tested last week. No code need to be changed to support FM v4 but only pubspec.yaml, so I am not planning to upload a dev version of FMLM. But you can use `dependency_overrides` to bypass the version constrain, for example:

```yaml
dependencies:
  flutter_map: ^4.0.0-dev.1
  flutter_map_location_marker: ^5.3.0

dependency_overrides:
  flutter_map: ^4.0.0-dev.1
```
