### ISSUE TITLE
LocationMarker plugin has not been setup correctly

### ISSUE THREAD

**Issue by anmolsudhir** [tlserver/flutter_map_location_marker#84]
Hi,

I'm new to flutter and was exploring flutter and flutter_map for a project. And getting the following error while using this package

<img width="200" alt="Screenshot 2023-09-23 at 14 46 09" src="https://github.com/tlserver/flutter_map_location_marker/assets/126346554/9c7f31e2-9928-46f9-a278-e382ac003685">

Below is my current pubspec.yaml file

```
name: my_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  flutter_map_location_marker: ^7.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

And this is the minimum example code taken from the example/ of this repository that I'm trying to run

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map_location_marker/flutter_map_location_marker.dart';
import 'package:latlong2/latlong.dart';

void main() {
  runApp(
    MaterialApp(
      home: MinimumExample(),
    ),
  );
}

class MinimumExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      options: MapOptions(
        center: const LatLng(0, 0),
        zoom: 1,
        maxZoom: 19,
      ),
      children: [
        TileLayer(
          urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          subdomains: const ['a', 'b', 'c'],
          maxZoom: 19,
        ),
        CurrentLocationLayer(),
      ],
    );
  }
}
```

It was working previously with version 7.0.4, and my pubspec.yml at that time was

```
name: my_app
description: A new Flutter project.

publish_to: 'none' 
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.4.5
  flutter_map: ^5.0.0
  flutter_map_location_marker: ^7.0.4
  vector_map_tiles: ^5.0.0
  flutter_map_tappable_polyline: ^5.0.0
  flutter_polyline_points: ^2.0.0
  flutter_map_animations: ^0.4.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

```
